rmw_dds_common/CMakeLists.txt, rmw_dds_common/package.xml
I created this PR as part of the effort to split `rosidl_generator` in two part `rosidl_generator_x` and `rosidl_runtime_x`
Header are now located in `rosidl_runtime_cpp` package not in the `rosild_generator_cpp` package.
As @dirk-thomas request in this issue https://github.com/ros2/rmw_dds_common/issues/9, `rosidl_generator_cpp` could not be a runtime dependency because it does not contain any `.so/dll/dylib`. I changed this in the `package.xml` to `<buildtool_depend>` and `buildtool_export_depend`
=> Changed rosidl_generator_cpp with rosidl_runtime_cpp

rmw_dds_common/include/rmw_dds_common/graph_cache.hpp, rmw_dds_common/src/graph_cache.cpp
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>
=> security-context -> enclave

rmw_dds_common/CMakeLists.txt, rmw_dds_common/package.xml, rmw_dds_common/test/test_graph_cache.cpp
Precisely what the title says. With these additions, test coverage for sources is > 90%. 
If we want to push for that final ~10%, we'll have to mock `rcutils` and `rmw` APIs.
=> Improve test coverage

rmw_dds_common/test/test_graph_cache.cpp
Precisely what the title says. A `GraphCache` test started failing after https://github.com/ros2/rcutils/pull/246 (see https://ci.ros2.org/view/nightly/job/nightly_linux_release/lastCompletedBuild/testReport/junit/rmw_dds_common/test_graph_cache/bad_arguments/). This patch re-orders assertions to deal with an initialized cache. It also stops relying on variable shadowing.
=> Fix graph cache tests.

rmw_dds_common/QUALITY_DECLARATION.md
This PR adds a link to REP-2006 (the Security Vulnerability Declaration) to the Quality Declaration for this repository.
Connects to ros2/ros2#924.
=> QD Security Vulnerability Declaration: REP 2006

rmw_dds_common/CMakeLists.txt, rmw_dds_common/test/test_graph_cache.cpp
Adding fault injection unit tests to rmw_dds_common. This should get coverage to about 99%. I'll post CI results soon.
Signed-off-by: Stephen Brawner <brawner@gmail.com>
=> Add fault injection macro unit tests

rmw_dds_common/CMakeLists.txt, rmw_dds_common/include/rmw_dds_common/time_utils.hpp, rmw_dds_common/src/time_utils.cpp, rmw_dds_common/test/test_time_utils.cpp
The RMW layer maintains the rmw_time_t's seconds and nanoseconds
values as 64-bit unsigned integers. However, the DDS standard
specifies the Time_t and Duration_t types with "long sec" and
"unsigned long nanosec", and the IDL to C++11 mapping states that
the C++ types for long and unsigned long are mapped to int32_t and
uint32_t, respectively. This difference can result in the seconds
(and/or nanoseconds) value being truncated and incorrect, causing
other downstream failures. This function can be used in different
RMW adaptation layers that interface to the DDS providers when
converting from rmw_time_to to the DDS Duration_t (or Time_t),
such as rmw_time_to_fast_rtps.
Signed-off-by: Michael Jeronimo <michael.jeronimo@openrobotics.org>
=> Create a utility function to limit rmw_time_t to 32-bit values

rmw_dds_common/CMakeLists.txt
The line length enforcement in ament_lint_cmake has been broken for some time, but will be fixed by ament/ament_lint#236. This change brings this package into compliance with a 120 column limit.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13645)](http://ci.ros2.org/job/ci_linux/13645/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8525)](http://ci.ros2.org/job/ci_linux-aarch64/8525/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11360)](http://ci.ros2.org/job/ci_osx/11360/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13709)](http://ci.ros2.org/job/ci_windows/13709/)
=> Shorten some excessively long lines of CMake

rmw_dds_common/CMakeLists.txt, rmw_dds_common/docs/FEATURES.md, rmw_dds_common/include/rmw_dds_common/qos.hpp, rmw_dds_common/src/qos.cpp, rmw_dds_common/test/test_qos.cpp
Given QoS profiles for a publisher and a subscription, this function
will return `true` if the profiles are compatible.
Compatible profiles implies that the subscription and publisher will
be able to communicate.
Connected to https://github.com/ros2/rmw/pull/299
=> Add function for checking QoS profile compatibility

rmw_dds_common/src/time_utils.cpp, rmw_dds_common/test/test_time_utils.cpp
This PR updates the implementation of `rmw_dds_common::clamp_rmw_time_to_dds_time()` to better comply with the DDS specification, which mandates that time values be normalized to have the "nanoseconds" component always < 1 second.
Quoting the relevant bit from the spec ([v1.4](), section 2.3.2):
> The two types used to represent time: Duration_t and Time_t are mapped into structures that contain fields for the second and the nanosecond parts. These types are further constrained to always use a ‘normalized’ representation for the time, that is, the nanosec field must verify 0 <= nanosec < 1000000000.
The updates limit the values produced by `rmw_dds_common::clamp_rmw_time_to_dds_time() to a maximum of {`INT_MAX` seconds, `10^9 - 1` nanoseconds}.
I came up with these changes while working …
=> Normalize rmw_time_t according to DDS spec

rmw_dds_common/CMakeLists.txt, rmw_dds_common/include/rmw_dds_common/security.hpp, rmw_dds_common/src/security.cpp, rmw_dds_common/test/test_security.cpp
All three of the in-tree DDS RMW implementation hard-code a
list of files in the security enclave.  Instead of doing this
in three separate places, add in a common function that finds
the set of files in the security enclave that are needed for
DDS security.
get_security_files() currently returns them in an unordered_map.
The main reason to use a map over a structure is ABI concerns;
it should be easy to add another field to the unordered_map,
whereas adding one to a structure would be harder.  (I intend
to add something to the map in the near future).  It's also
not performance sensitive, so the extra string allocations
shouldn't hurt performance.
=> Add a common function for security files.

rmw_dds_common/src/security.cpp
I get warnings from clang when compiling the latest master:
```
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rmw_dds_common/rmw_dds_common/src/security.cpp:38:52: error: loop variable 'el' has type 'const std::pair<std::string, std::string> &' (aka 'const pair<basic_string<char, char_traits<char>, allocator<char> >, basic_string<char, char_traits<char>, allocator<char> > > &') but is initialized with type 'const std::__1::__hash_map_const_iterator<std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, std::__1::basic_string<char> >, void *> *> >::value_type' (aka 'const pair<const std::__1::basic_string<char>, std::__1::basic_string<char> >') resulting in a copy [-Werror,-Wrange-loop-construct]
for (const …
```
=> silence clang warning (`range-loop-construct`)

rmw_dds_common/src/security.cpp, rmw_dds_common/test/test_security.cpp
At least Fast-RTPS and CycloneDDS support Certificate
Revocation Lists, so add it as one of the possible files
in the enclave.  Note that it is an optional file; if
an enclave doesn't have it, then the key will be missing
from the returned map.
Besides the maintainers of this package, also pinging @ruffsl , @mikaelarguedas , and @SidFaber .  The addition of this file is essentially expanding the on-disk "API" of an SROS2 security enclave to include the `crl.pem` file, so I'd appreciate any feedback that you may have.
=> Add support for Certificate Revocation List files.

README.md, rmw_dds_common/Doxyfile, rmw_dds_common/README.md, rmw_dds_common/include/rmw_dds_common/gid_utils.hpp, rmw_dds_common/include/rmw_dds_common/graph_cache.hpp, rmw_dds_common/include/rmw_dds_common/qos.hpp
Precisely what the title says. This patch:
- Updates the `rmw_dds_common`'s Doxyfile.
- Cleans up `rmw_dds_common` API doc blocks.
- Rearranges a few `md` files to avoid path issues.
=> Fix up rmw_dds_common documentation when using rosdoc2

rmw_dds_common/test/test_security.cpp
Relates to https://github.com/ament/ament_lint/pull/324
=> Fix include order for cpplint

rmw_dds_common/CMakeLists.txt
Part of https://github.com/ros2/ros2/issues/1150 - this installs headers to a unique directory in a merged workspace.
=> Install headers to include/${PROJECT_NAME}

rmw_dds_common/CMakeLists.txt
This package is currently hard-coding the include directories for the generator packages it depends on. This makes it use `rosidl_get_typesupport_target()` insteadl. I also made it use `target_link_libraries` instead of `ament_target_dependencies`.
I think this depends on ros2/rosidl_typesupport#123, but I don't remember why (**Edit:** I think it needs that cleanup PR to get the dependency on rosidl_generator_c transitively from rosidl_generator_cpp instead of hard coding both)
=> Use rosidl_get_typesupport_target and target_link_libraries

rmw_dds_common/CMakeLists.txt
The target generated by `rosidl_typesupport_cpp` depends on the target generated by `rosidl_generator_cpp`, and adds a library implementing things necessary to use C++ generated messages
=> Depend on target generated by rosidl_typesupport_cpp

rmw_dds_common/CMakeLists.txt, rmw_dds_common/include/rmw_dds_common/qos.hpp, rmw_dds_common/src/qos.cpp, rmw_dds_common/test/test_qos.cpp
Connects to https://github.com/ros2/rmw/pull/320
Given a QoS profile and set of endpoints for the same topic, overwrite any policies set to
BEST_AVAILABLE with a policy such that it matches all endpoints while maintaining a high
level of service.
Add testable functions for updating BEST_AVAILABLE policies,
- qos_profile_get_best_available_for_subscription
- qos_profile_get_best_available_for_publisher
and add convenience functions that actual query the graph for RMW implementations to use,
- qos_profile_get_best_available_for_topic_subscription
- qos_profile_get_best_available_for_topic_publisher
=> Add functions for resolving 'best available' QoS policies

rmw_dds_common/test/test_qos.cpp
In particular, make sure to free topic endpoint info on all paths, and also make sure to reset errors after a failure. Issues pointed out by running under valgrind.
=> Minor cleanups of test_qos.

rmw_dds_common/CMakeLists.txt
The two reasons to do this are:
1. So that we can compile rmw_dds_common with the clang static analyzer. As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
2. So we can build with a newer version of gtest which requires this.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version. So set this as well.
=> Update rmw_dds_common to C++17.

rmw_dds_common/test/benchmark/benchmark_graph_cache.cpp
This is just to keep clang static analysis happy.
=> Mark benchmark _ as unused.

rmw_dds_common/CMakeLists.txt, rmw_dds_common/include/rmw_dds_common/graph_cache.hpp, rmw_dds_common/include/rmw_dds_common/qos.hpp, rmw_dds_common/package.xml, rmw_dds_common/src/graph_cache.cpp, rmw_dds_common/src/qos.cpp, rmw_dds_common/test/benchmark/benchmark_graph_cache.cpp, rmw_dds_common/test/test_graph_cache.cpp, rmw_dds_common/test/test_qos.cpp
Part of ros2/ros2#1159
Depends on ros2/rosidl#722
Depends on ros2/rmw#348
Updates the `GraphCache`'s `EntityInfo` struct with a new field `topic_type_hash` that can be filled out during discovery by implementations, which is passed through to `rmw_topic_endpoint_info`.
Adds utility functions `parse_type_hash_from_user_data_qos` and `encode_type_hash_for_user_data_qos` for using this value as a `USER_DATA` QoS value during discovery.
=> Type hash in GraphCache, user_data encoding tools

rmw_dds_common/CMakeLists.txt, rmw_dds_common/include/rmw_dds_common/context.hpp, rmw_dds_common/src/context.cpp
Its intent is to avoid using mutex directly outside, and decrease the replicated code about updating graph in RMWs.
=> make a new private mutex and add updating graph methods

rmw_dds_common/include/rmw_dds_common/security.hpp, rmw_dds_common/src/security.cpp, rmw_dds_common/test/test_security.cpp
This implements ros2/design#332
=> Add pkcs11 support to get_security_files
