rmw_dds_common/test/test_graph_cache.cpp

Fixes #5.
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9780)](https://ci.ros2.org/job/ci_windows/9780/)

Fix windows warning

---

rmw_dds_common/CMakeLists.txt
rmw_dds_common/test/allocator_testing_utils.h
rmw_dds_common/test/test_gid_utils.cpp
rmw_dds_common/test/test_graph_cache.cpp

Increased the code coverage.
- Added failing allocators
- Untested methods
- get_readers_info_by_topic
- get_writers_info_by_topic
- Operators
- << 
- ==

Increasing code coverage

---

rmw_dds_common/CMakeLists.txt

export targets in a addition to include directories / libraries

---

README.md
rmw_dds_common/QUALITY_DECLARATION.md

Adding a current-level quality declaration and updating the readme.
Signed-off-by: Stephen Brawner <brawner@gmail.com>

Updating README and adding QUALITY_DECLARATION for current QL level

---

README.md

Precisely what the title says.

Document rmw_dds_common package features.

---

rmw_dds_common/Doxyfile

Added Doxyfile to include the public API documentation in docs.ros2.org

Added Doxyfile

---

rmw_dds_common/QUALITY_DECLARATION.md

Precisely what the title says.

Update Quality Declaration to QL3.

---

rmw_dds_common/Doxyfile
rmw_dds_common/include/rmw_dds_common/context.hpp
rmw_dds_common/include/rmw_dds_common/gid_utils.hpp
rmw_dds_common/include/rmw_dds_common/graph_cache.hpp

Fixed some doxygen warnings
@ivanpauno and/or @hidmic do you mind to fix the rest of the doxygen warnings (as you are the main contributors of the repo) ? 
```bash
src/ros2/rmw_dds_common/rmw_dds_common/include/rmw_dds_common/graph_cache.hpp:529: warning: Compound rmw_dds_common::EntityInfo is not documented.
src/ros2/rmw_dds_common/rmw_dds_common/include/rmw_dds_common/graph_cache.hpp:522: warning: Compound rmw_dds_common::ParticipantInfo is not documented.
src/ros2/rmw_dds_common/rmw_dds_common/include/rmw_dds_common/context.hpp:31: warning: Compound rmw_dds_common::Context is not documented.
src/ros2/rmw_dds_common/rmw_dds_common/include/rmw_dds_common/graph_cache.hpp:344: warning: Member DemangleFunctionT (typedef) of class rmw_dds_common::GraphCache is not documented. …
```

Fixed some doxygen warnings

---

rmw_dds_common/src/graph_cache.cpp

Just a minor fix. (Not to open an issue)
Signed-off-by: Chen.Lihui <lihui.chen@sony.com>

Fix potential memory leak

---

rmw_dds_common/CMakeLists.txt
rmw_dds_common/benchmark/benchmark_graph_cache.cpp
rmw_dds_common/package.xml
rmw_dds_common/test/benchmark/benchmark_graph_cache.cpp

Added benchmark test to rmw_dds_common, in particular to `GraphCache` class.
- get_writer_count
- get_reader_count
- get_writer_names_and_types_by_node
- get_reader_names_and_types_by_node
- get_names_and_types
- get_readers_info_by_topic
- get_writers_info_by_topic
- associate/dissociate_reader
- add/remove_entity
- add/remove node
- add/remove participant

Added benchmark test to rmw_dds_common

---

rmw_dds_common/QUALITY_DECLARATION.md

Precisely what the title says.

Update Quality Declaration to QL2.

---

rmw_dds_common/QUALITY_DECLARATION.md

Updated performance section QD

---

README.md

Update QD to 2 In README.md

---

rmw_dds_common/CMakeLists.txt
rmw_dds_common/package.xml
rmw_dds_common/test/benchmark/benchmark_graph_cache.cpp

[Backport Foxy] Added benchmark test to rmw_dds_common (#29)

---

rmw_dds_common/CMakeLists.txt
rmw_dds_common/test/test_graph_cache.cpp

* Add fault injection macro unit tests
Signed-off-by: Stephen Brawner <brawner@gmail.com>
* target definitions
Signed-off-by: Stephen Brawner <brawner@gmail.com>
* PR Fixup
Signed-off-by: Stephen Brawner <brawner@gmail.com>

Add fault injection macro unit tests (#27)

---

README.md
rmw_dds_common/QUALITY_DECLARATION.md

Signed-off-by: Stephen Brawner <brawner@gmail.com>

Update QD to QL 1

---

rmw_dds_common/test/test_graph_cache.cpp

Fixes #41.
Signed-off-by: y-okumura-isp <y-okumura@isp.co.jp>

Fix test_graph_cache ASAN errors (#41)

---

rmw_dds_common/QUALITY_DECLARATION.md

Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52

Updating Quality Declaration

---

rmw_dds_common/QUALITY_DECLARATION.md

Fix one more instance of index.ros.org.

---

rmw_dds_common/package.xml

Update maintainers 🔥

---

rmw_dds_common/CMakeLists.txt
rmw_dds_common/src/security.cpp
rmw_dds_common/test/test_security.cpp

Because the package will be no longer available. https://github.com/ros2/rcpputils/issues/164

Just remove rcpputils::fs dependency
